//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "ip_blacklist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(ignore, column_type = "custom(\"inet\")", select_as = "text")]
    pub subnet: String,
    #[sea_orm(column_type = "Text")]
    pub comment: String,
}

impl ActiveModelBehavior for ActiveModel {}
