/*
 * Copyright 2026 Jhe-An Lee
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::ip_blacklist::Entity as IpBlacklist;
pub use super::ip_whitelist::Entity as IpWhitelist;
pub use super::mikro_orm_migrations::Entity as MikroOrmMigrations;
pub use super::settings::Entity as Settings;
pub use super::tunnel_sessions::Entity as TunnelSessions;
pub use super::tunnel_status::Entity as TunnelStatus;
pub use super::tunnel_users::Entity as TunnelUsers;
