//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

pub use super::ip_blacklist::Entity as IpBlacklist;
pub use super::ip_whitelist::Entity as IpWhitelist;
pub use super::settings::Entity as Settings;
pub use super::statistics::Entity as Statistics;
pub use super::user::Entity as User;
