/*
 * Copyright 2026 Jhe-An Lee
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use sea_orm::DerivePartialModel;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tunnel_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", unique)]
    pub token: String,
    #[sea_orm(column_type = "Text")]
    pub hashed_password: String,
    pub label: Vec<String>,
    pub last_login: DateTime,
    pub administrator: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tunnel_sessions::Entity")]
    TunnelSessions,
}

impl Related<super::tunnel_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TunnelSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(DerivePartialModel, Serialize)]
#[sea_orm(entity = "super::tunnel_users::Entity")]
pub struct ListUserPartialModel {
    pub id: String,
    pub username: String,
    pub label: Vec<String>,
    pub last_login: DateTime,
    pub administrator: bool,
}
