//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tunnel_status")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub bucket_start: DateTime,
    pub sample_count: i64,
    pub active_service_avg: i64,
    pub active_service_max: i64,
    pub external_connection_avg: i64,
    pub external_connection_max: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
