/*
 * Copyright 2026 Jhe-An Lee
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tunnel_sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "tunnel_sessions_user_id_bucket_start_tunnel_client_unique")]
    pub user_id: String,
    #[sea_orm(unique_key = "tunnel_sessions_user_id_bucket_start_tunnel_client_unique")]
    pub bucket_start: DateTime,
    #[sea_orm(
        column_type = "custom(\"inet\")",
        unique_key = "tunnel_sessions_user_id_bucket_start_tunnel_client_unique"
    )]
    pub tunnel_client: IpNetwork,
    pub inbound: i64,
    pub outbound: i64,
    pub external_connection_count: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tunnel_users::Entity",
        from = "Column::UserId",
        to = "super::tunnel_users::Column::Id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    TunnelUsers,
}

impl Related<super::tunnel_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TunnelUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
